permalink: /:categories/:year/:month/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
future: true

title : Alfan Presekal Profile
tagline:
author :
  name : Alfan Presekal
  email : alfanpresekal@gmail.com
  github : alfanpresekal
  twitter : alfanpresekal

production_url : presekal.com

collections:
  events:
    output: true
    sort_by: date
    permalink: /:collection/:year/:month/:day/:title/
  posts:
    output: true
    permalink: /:collection/:year/:month/:title/
  researchlines:
    output: true
    permalink: /research-lines/:title/


